<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>await</title>
  </head>
  <body>
    <script>
      async function main() {
        // await 右侧的表达式一般为 promise 对象, 但也可以是其它的值
        // await 只能在async函数中使用, 但是async函数中可以没有await

        // 如果表达式是 成功的 promise 对象, await 返回的是 promise 成功的值
        // 如果表达式是 失败的 promise 对象, 则会抛出异常, 需要通过 try...catch 捕获处理

        // 如果表达式是其它值, 直接将此值作为 await 的返回值

        //1. 右侧为promise的情况
        let p = await new Promise((resolve, reject) => {
          resolve("OK");
        });
        console.log(p);

        //2. 右侧为其他类型的数据
        let res2 = await 20;
        console.log(res2);

        //3. 如果promise是失败的状态
        try {
          let res3 = await await new Promise((resolve, reject) => {
            reject("Error");
          });
        } catch (e) {
          console.log(e);
        }
      }

      main();
    </script>
  </body>
</html>
